/* Generated By:JavaCC: Do not edit this line. CMMParserTreeConstants.java Version 5.0 */
public interface CMMParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLAR_STMT = 1;
  public int JJTTYPE = 2;
  public int JJTVARIABLE = 3;
  public int JJTPARA_STMT = 4;
  public int JJTSTMT = 5;
  public int JJTINITIALVALUE = 6;
  public int JJTRIGHTVAL = 7;
  public int JJTLOGICAL_EXPRESSION = 8;
  public int JJTLOGICAL_FACTOR1 = 9;
  public int JJTLOGICAL_FACTOR2 = 10;
  public int JJTLOGICAL_SYMBOL = 11;
  public int JJTMANTCONSTANT = 12;
  public int JJTCONSTANT_CLOSURE = 13;
  public int JJTSTMT_CLOSURE = 14;
  public int JJTCO_FUNCTION = 15;
  public int JJTFUCTIONBLOCK = 16;
  public int JJTSTMT_EXPRESSION_CLOSURE = 17;
  public int JJTSTMT_EXPRESSION = 18;
  public int JJTFUCTIONBLOCK_CLOSURE = 19;
  public int JJTIF_STATEMENT = 20;
  public int JJTIFBLOCK = 21;
  public int JJTELSE_STATEMENT = 22;
  public int JJTRETURN_STATEMENT = 23;
  public int JJTPRIN_FUNCTION = 24;
  public int JJTSCAN_FUNCTION = 25;
  public int JJTPARA_LIST = 26;
  public int JJTPARA_CLOSURE = 27;
  public int JJTASTAMENT = 28;
  public int JJTPARA = 29;
  public int JJTFORLOOP = 30;
  public int JJTFORBLOCK = 31;
  public int JJTASSIGNMENT = 32;
  public int JJTASSIGN = 33;
  public int JJTWHILELOOP = 34;
  public int JJTWHILEBLOCK = 35;
  public int JJTARRAYINDEX = 36;
  public int JJTFACTOR = 37;
  public int JJTCONSTANT = 38;
  public int JJTARITH_EXPRESSION = 39;
  public int JJTFACTORS = 40;
  public int JJTFACTOR1 = 41;
  public int JJTFACTOR_RECURSION = 42;
  public int JJTTERM = 43;


  public String[] jjtNodeName = {
    "Program",
    "declar_stmt",
    "type",
    "variable",
    "para_stmt",
    "stmt",
    "initialvalue",
    "rightVal",
    "logical_expression",
    "logical_factor1",
    "logical_factor2",
    "logical_symbol",
    "mantConstant",
    "constant_closure",
    "stmt_closure",
    "co_function",
    "fuctionBlock",
    "stmt_expression_closure",
    "stmt_expression",
    "fuctionBlock_closure",
    "if_statement",
    "ifblock",
    "else_statement",
    "return_statement",
    "prin_function",
    "scan_function",
    "para_list",
    "para_closure",
    "astament",
    "para",
    "forloop",
    "forblock",
    "assignment",
    "assign",
    "whileloop",
    "whileblock",
    "arrayIndex",
    "factor",
    "constant",
    "arith_expression",
    "factors",
    "factor1",
    "factor_recursion",
    "term",
  };
}
/* JavaCC - OriginalChecksum=31a9a75f64031d99e763eb52cc36b0c9 (do not edit this line) */
